Repository datadrivers/terraform-provider-nexus, pull requests merged in 2021-12, with the labels that each got.

#152 fix(dependabot): corrected package-ecosystem gomod
  .github/dependabot.yml
Labels: bug

#153 chore(codeql): enabled codeql-analysis workflow
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#157 chore(README): added CodeQL badge
  README.md
Labels: documentation

#159 [Issue:#123] Implement nexus_repository_yum_hosted
  docs/data-sources/repository_yum_hosted.md
  docs/resources/repository_yum_hosted.md
  nexus/data_source_repository_yum_hosted.go
  nexus/data_source_repository_yum_hosted_test.go
  nexus/provider.go
  nexus/resource_repository.go
  nexus/resource_repository_test.go
  nexus/resource_repository_yum_hosted.go
  nexus/resource_repository_yum_hosted_test.go
Labels: enhancement
